# Generated by Django 5.1.15 on 2026-05-02 17:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("first_name", models.CharField(max_length=80)),
                ("last_name", models.CharField(blank=True, default="", max_length=80)),
                ("email", models.EmailField(blank=True, db_index=True, default="", max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=40)),
                ("title", models.CharField(blank=True, default="", max_length=120)),
                ("tags", models.JSONField(blank=True, default=list)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("website", models.URLField(blank=True, default="")),
                ("industry", models.CharField(blank=True, default="", max_length=80)),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        choices=[("smb", "1–50"), ("mid", "51–500"), ("enterprise", "501+")],
                        default="",
                        max_length=16,
                    ),
                ),
                (
                    "annual_revenue",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                ("address", models.JSONField(blank=True, default=dict)),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_companies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Companies",
                "abstract": False,
            },
        ),
    ]
