# Generated by Django 5.1.15 on 2026-05-02 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contacts",
                to="customers.company",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_contacts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["tenant", "name"], name="customers_c_tenant__56b33b_idx"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["tenant", "email"], name="customers_c_tenant__72aae0_idx"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["tenant", "last_name", "first_name"], name="customers_c_tenant__cfea17_idx"
            ),
        ),
    ]
