# Generated by Django 5.1.15 on 2026-05-02 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"ordering": ("-created_at",), "verbose_name_plural": "Companies"},
        ),
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ("-created_at",)},
        ),
    ]
