# Generated by Django 5.1.15 on 2026-05-02 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
            ),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                fields=["tenant", "content_type", "object_id"], name="core_note_tenant__56d5a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                fields=["tenant", "created_at"], name="core_note_tenant__ecd79a_idx"
            ),
        ),
    ]
