# Generated by Django 5.1.15 on 2026-05-02 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leads", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["tenant", "status"], name="leads_lead_tenant__054659_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["tenant", "score"], name="leads_lead_tenant__f00a09_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["tenant", "email"], name="leads_lead_tenant__0cfaba_idx"),
        ),
    ]
