# Generated by Django 5.1.15 on 2026-05-02 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("deals", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
            ),
        ),
        migrations.AddField(
            model_name="pipeline",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="pipeline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deals",
                to="deals.pipeline",
            ),
        ),
        migrations.AddField(
            model_name="stage",
            name="pipeline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stages",
                to="deals.pipeline",
            ),
        ),
        migrations.AddField(
            model_name="stage",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="stage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="deals", to="deals.stage"
            ),
        ),
        migrations.AddIndex(
            model_name="pipeline",
            index=models.Index(
                fields=["tenant", "is_default"], name="deals_pipel_tenant__cc807d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pipeline",
            unique_together={("tenant", "name")},
        ),
        migrations.AddIndex(
            model_name="stage",
            index=models.Index(
                fields=["pipeline", "position"], name="deals_stage_pipelin_79d69f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(fields=["tenant", "status"], name="deals_deal_tenant__6a3b02_idx"),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(fields=["tenant", "stage"], name="deals_deal_tenant__8c43c3_idx"),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(fields=["tenant", "owner"], name="deals_deal_tenant__f4ab9a_idx"),
        ),
    ]
