# Generated by Django 5.1.15 on 2026-05-02 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rbac", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_roles",
                to="tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["tenant", "slug"], name="rbac_role_tenant__702453_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="role",
            unique_together={("tenant", "slug")},
        ),
    ]
