# Generated by Django 5.1.15 on 2026-05-02 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiinvocation",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
            ),
        ),
        migrations.AddIndex(
            model_name="aiinvocation",
            index=models.Index(
                fields=["tenant", "use_case", "created_at"], name="ai_aiinvoca_tenant__6f8d07_idx"
            ),
        ),
    ]
