# Generated by Django 5.1.15 on 2026-05-02 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlog",
            options={"ordering": ("-created_at",)},
        ),
    ]
